<?php
/**
 * ZF3 book Simple CMS Training Application
 *
 * @author     Ralf Eggert <ralf@travello.de>
 * @link       https://github.com/zf3buch/simple-cms
 * @license    http://opensource.org/licenses/MIT The MIT License (MIT)
 *
 */

use CategoryModel\Entity\CategoryEntity;
use PageModel\Entity\PageEntity;

/** @var CategoryEntity $category */
$category = $this->category;

$this->headTitle('Kategorie' . $category->getName());
$this->h1('Kategorie' . $category->getName());
?>
<p class="text-center">
  <a class="btn btn-default" href="<?= $this->url('home'); ?>">
    <i class="fa fa-arrow-circle-left"></i> Zurück zur Startseite
  </a>
</p>

<div class="row">
  <?php /** @var PageEntity $page */ ?>
  <?php foreach ($this->pageList as $page) : ?>
    <?php
    $text = strip_tags($page->getText());
    $text = implode(' ', array_slice(explode(' ', $text), 0, 50));

    $pageUrl     = $this->url('page', ['url' => $page->getUrl()]);
    $categoryUrl = $this->url(
        'category', ['url' => $page->getCategory()->getUrl()]
    );
    ?>
    <div class="col-sm-6">
      <div class="panel panel-primary">
        <div class="panel-heading clearfix">
          <strong>
            <a href="<?= $pageUrl; ?>">
              <?= $page->getTitle() ?>
            </a>
          </strong>
        </div>
        <div class="panel-body">
          <div class="col-sm-4">
            <img src="<?= $page->getCategory()->getImage() ?>"
                 class="img-responsive center-block">
          </div>
          <p><?= $text; ?> ...</p>
          <p class="text-center">
            <a href="<?= $pageUrl; ?>" class="btn btn-primary">
              Seite anzeigen
            </a>
            <a href="<?= $categoryUrl; ?>" class="btn btn-primary">
              Alle <?= $page->getCategory()->getName() ?> Seiten
            </a>
          </p>
        </div>
      </div>
    </div>
  <?php endforeach; ?>
</div>

<p class="text-center">
  <a class="btn btn-default" href="<?= $this->url('home'); ?>">
    <i class="fa fa-arrow-circle-left"></i> Zurück zur Startseite
  </a>
</p>
