<?php
/**
 * ZF3 book Simple CMS Training Application
 *
 * @author     Ralf Eggert <ralf@travello.de>
 * @link       https://github.com/zf3buch/simple-cms
 * @license    http://opensource.org/licenses/MIT The MIT License (MIT)
 *
 */

use PageModel\Entity\PageEntity;

/** @var PageEntity $page */
$page = $this->page;

$listLink = $this->url(
    'category', ['url' => $page->getCategory()->getUrl()], true
);
$listText = 'Zurück zur Kategorie ' . $page->getCategory()->getName();

$this->headTitle($page->getTitle());
?>
<div class="page-header">
  <h1><?= $page->getTitle() ?></h1>
</div>

<p class="text-center">
  <a class="btn btn-default" href="<?= $listLink; ?>">
    <i class="fa fa-arrow-circle-left"></i> <?= $listText; ?>
  </a>
</p>
<div class="panel panel-primary">
  <div class="panel-heading clearfix">
    <div class="left-text">
      <strong><?= $page->getTitle(); ?></strong>
    </div>
    <div class="right-text">
      Autor: <?= $page->getAuthor(); ?>
    </div>
  </div>
  <div class="panel-body">
    <div class="col-sm-9">
      <p><?= $page->getText(); ?></p>
    </div>
    <div class="col-sm-3 category">
      <p>
        <a href="<?= $listLink ?>">
          <img class="img-responsive" src="<?= $page->getCategory()->getImage() ?>">
        </a>
      </p>
      <h5><strong>Kategorie: <?= $page->getCategory()->getName() ?></strong></h5>
      <p><?= $page->getCategory()->getDescription() ?></p>
    </div>
  </div>
  <div class="panel-footer clearfix">
    <div class="text-center">
      <div class="label label-primary">
        Letzte Änderung: <?= $page->getUpdated()->format('d.m.Y H:i:s') ?>
      </div>
    </div>
  </div>
</div>
<p class="text-center">
  <a class="btn btn-default" href="<?= $listLink; ?>">
    <i class="fa fa-arrow-circle-left"></i> <?= $listText; ?>
  </a>
</p>
