<?php
/**
 * ZF3 book Simple CMS Training Application
 *
 * @author     Ralf Eggert <ralf@travello.de>
 * @link       https://github.com/zf3buch/simple-cms
 * @license    http://opensource.org/licenses/MIT The MIT License (MIT)
 *
 */

use PageBackend\Form\PageFormInterface;

/** @var PageFormInterface $form */
$form = $this->pageForm;

$listLink = $this->url('page-backend', [], true);

$this->headTitle('page_backend_title_display_add');
$this->h1('page_backend_h1_display_add');

$this->inlineScript()->prependFile(
    '/assets/vendor/ckeditor/ckeditor.js', 'text/javascript'
);
$this->inlineScript()->appendScript('CKEDITOR.replace("page_text");');
?>
<p>
  <a href="<?= $listLink ?>" class="btn btn-default">
    <i class="fa fa-list"></i>
    <span class="hidden-xs hidden-sm">
      <?= $this->translate('page_backend_action_overview') ?>
    </span>
  </a>
</p>
<div class="well">
  <?= $this->bootstrapForm($form); ?>
</div>
