<?php
/**
 * ZF3 book Simple CMS Training Application
 *
 * @author     Ralf Eggert <ralf@travello.de>
 * @link       https://github.com/zf3buch/simple-cms
 * @license    http://opensource.org/licenses/MIT The MIT License (MIT)
 *
 */

$listLink = $this->url('page-backend', [], true);

$this->headTitle('Seite anlegen');
?>
<div class="page-header">
  <h1>Seite anlegen</h1>
</div>

<p>
  <a href="<?= $listLink ?>" class="btn btn-default">
    <i class="fa fa-list"></i>
    <span class="hidden-xs hidden-sm">Übersicht</span>
  </a>
</p>
<div class="well">
  In Kürze mehr...
</div>
