<?php
/**
 * ZF3 book Simple CMS Training Application
 *
 * @author     Ralf Eggert <ralf@travello.de>
 * @link       https://github.com/zf3buch/simple-cms
 * @license    http://opensource.org/licenses/MIT The MIT License (MIT)
 *
 */

use PageModel\Entity\PageEntity;

/** @var PageEntity $page */
$page = $this->page;

$listLink    = $this->url('page-backend', [], true);
$showLink    = $this->url(
    'page-backend/show', ['id' => $page->getId()], true
);
$editLink    = $this->url(
    'page-backend/modify', ['action' => 'edit', 'id' => $page->getId()], true
);
$deleteLink  = $this->url(
    'page-backend/modify', ['action' => 'delete', 'id' => $page->getId()], true
);
$approveLink = $this->url(
    'page-backend/modify', ['action' => 'approve', 'id' => $page->getId()], true
);
$blockLink   = $this->url(
    'page-backend/modify', ['action' => 'block', 'id' => $page->getId()], true
);

$this->headTitle('Seite freigeben');
?>
<div class="page-header">
  <h1>Seite freigeben</h1>
</div>

<p>
  <a href="<?= $showLink ?>" class="btn btn-default">
    <i class="fa fa-file-text-o"></i>
    <span class="hidden-xs hidden-sm">Anzeigen</span>
  </a>
  <a href="<?= $editLink ?>" class="btn btn-default">
    <i class="fa fa-pencil"></i>
    <span class="hidden-xs hidden-sm">Bearbeiten</span>
  </a>
  <a href="<?= $deleteLink ?>" class="btn btn-default">
    <i class="fa fa-trash-o"></i>
    <span class="hidden-xs hidden-sm">Löschen</span>
  </a>
  <a href="<?= $approveLink ?>" class="btn btn-primary">
    <i class="fa fa-thumbs-o-up"></i>
    <span class="hidden-xs hidden-sm">Freigeben</span>
  </a>
  <a href="<?= $blockLink ?>" class="btn btn-default">
    <i class="fa fa-thumbs-o-down"></i>
    <span class="hidden-xs hidden-sm">Sperren</span>
  </a>
  <a href="<?= $listLink ?>" class="btn btn-default">
    <i class="fa fa-list"></i>
    <span class="hidden-xs hidden-sm">Übersicht</span>
  </a>
</p>
<div class="alert alert-danger">
  <p>
    <strong>Möchten Sie diese Seite freigeben?</strong>
  </p>
  <p>
    <a class="btn btn-danger" href="<?= $approveLink ?>?approve=yes">
      Seite freigeben
    </a>
    <a class="btn btn-default" href="<?= $showLink ?>">
      Abbrechen
    </a>
  </p>
</div>
<div class="well">
  <form class="form-horizontal">
    <div class="form-group">
      <label class="col-sm-2 control-label">Kategorie</label>
      <div class="col-sm-10 form-control-static">
        <?= $page->getCategory()->getName() ?>
      </div>
    </div>
    <div class="form-group">
      <label class="col-sm-2 control-label">Angelegt</label>
      <div class="col-sm-10 form-control-static">
        <?= $page->getCreated()->format('d.m.Y H:i:s') ?>
      </div>
    </div>
    <div class="form-group">
      <label class="col-sm-2 control-label">Geändert</label>
      <div class="col-sm-10 form-control-static">
        <?= $page->getUpdated()->format('d.m.Y H:i:s') ?>
      </div>
    </div>
    <div class="form-group">
      <label class="col-sm-2 control-label">Status</label>
      <div class="col-sm-10 form-control-static">
        <?= $page->getStatus() ?>
      </div>
    </div>
    <div class="form-group">
      <label class="col-sm-2 control-label">Autor</label>
      <div class="col-sm-10 form-control-static">
        <?= $page->getAuthor() ?>
      </div>
    </div>
    <div class="form-group">
      <label class="col-sm-2 control-label">Titel</label>
      <div class="col-sm-10 form-control-static">
        <?= $page->getTitle() ?>
      </div>
    </div>
    <div class="form-group">
      <label class="col-sm-2 control-label">Text</label>
      <div class="col-sm-10 form-control-static">
        <?= $page->getText() ?>
      </div>
    </div>
  </form>
</div>
