<?php
/**
 * ZF3 book Simple CMS Training Application
 *
 * @author     Ralf Eggert <ralf@travello.de>
 * @link       https://github.com/zf3buch/simple-cms
 * @license    http://opensource.org/licenses/MIT The MIT License (MIT)
 *
 */

use PageBackend\Form\PageFormInterface;
use PageModel\Entity\PageEntity;

/** @var PageFormInterface $form */
$form = $this->pageForm;

/** @var PageEntity $page */
$page = $this->page;

$listLink    = $this->url('page-backend', [], true);
$showLink    = $this->url(
    'page-backend/show', ['id' => $page->getId()], true
);
$editLink    = $this->url(
    'page-backend/modify', ['action' => 'edit', 'id' => $page->getId()], true
);
$deleteLink  = $this->url(
    'page-backend/modify', ['action' => 'delete', 'id' => $page->getId()], true
);
$approveLink = $this->url(
    'page-backend/modify', ['action' => 'approve', 'id' => $page->getId()], true
);
$blockLink   = $this->url(
    'page-backend/modify', ['action' => 'block', 'id' => $page->getId()], true
);

$this->headTitle('Seite bearbeiten');
$this->h1('Seite bearbeiten');

$this->inlineScript()->prependFile(
    '/assets/vendor/ckeditor/ckeditor.js', 'text/javascript'
);
$this->inlineScript()->appendScript('CKEDITOR.replace("page_text");');
?>

<p>
  <a href="<?= $showLink ?>" class="btn btn-default">
    <i class="fa fa-file-text-o"></i>
    <span class="hidden-xs hidden-sm">Anzeigen</span>
  </a>
  <a href="<?= $editLink ?>" class="btn btn-primary">
    <i class="fa fa-pencil"></i>
    <span class="hidden-xs hidden-sm">Bearbeiten</span>
  </a>
  <a href="<?= $deleteLink ?>" class="btn btn-default">
    <i class="fa fa-trash-o"></i>
    <span class="hidden-xs hidden-sm">Löschen</span>
  </a>
  <a href="<?= $approveLink ?>" class="btn btn-default">
    <i class="fa fa-thumbs-o-up"></i>
    <span class="hidden-xs hidden-sm">Freigeben</span>
  </a>
  <a href="<?= $blockLink ?>" class="btn btn-default">
    <i class="fa fa-thumbs-o-down"></i>
    <span class="hidden-xs hidden-sm">Sperren</span>
  </a>
  <a href="<?= $listLink ?>" class="btn btn-default">
    <i class="fa fa-list"></i>
    <span class="hidden-xs hidden-sm">Übersicht</span>
  </a>
</p>
<?php
$staticElements = [
    [
        'label' => 'Angelegt',
        'value' => $page->getCreated()->format('d.m.Y H:i:s'),
    ],
    [
        'label' => 'Geändert',
        'value' => $page->getUpdated()->format('d.m.Y H:i:s'),
    ],
    [
        'label' => 'Status',
        'value' => $page->getStatus(),
    ],
    [
        'label' => 'Kategorie',
        'value' => $page->getCategory()->getName(),
    ],
];
?>
<div class="well">
  <?= $this->bootstrapForm($form, $staticElements); ?>
</div>
