<?php
/**
 * ZF3 book Simple CMS Training Application
 *
 * @author     Ralf Eggert <ralf@travello.de>
 * @link       https://github.com/zf3buch/simple-cms
 * @license    http://opensource.org/licenses/MIT The MIT License (MIT)
 *
 */

use CategoryBackend\Form\CategoryFormInterface;

/** @var CategoryFormInterface $form */
$form = $this->categoryForm;

$listLink = $this->url('category-backend', [], true);

$this->headTitle('Kategorien anlegen');
$this->h1('Kategorien anlegen');

$this->inlineScript()->prependFile(
    '/assets/vendor/ckeditor/ckeditor.js', 'text/javascript'
);
$this->inlineScript()->appendScript('CKEDITOR.replace("category_description");');
?>
<p>
  <a href="<?= $listLink ?>" class="btn btn-default">
    <i class="fa fa-list"></i>
    <span class="hidden-xs hidden-sm">Übersicht</span>
  </a>
</p>
<div class="well">
  <?= $this->bootstrapForm($form); ?>
</div>
