<?php
/**
 * ZF3 book Simple CMS Training Application
 *
 * @author     Ralf Eggert <ralf@travello.de>
 * @link       https://github.com/zf3buch/simple-cms
 * @license    http://opensource.org/licenses/MIT The MIT License (MIT)
 *
 */

use CategoryBackend\Form\CategoryFormInterface;

/** @var CategoryFormInterface $form */
$form = $this->categoryForm;

$listLink = $this->url('category-backend', [], true);

$this->headTitle('Kategorien anlegen');
?>
<div class="page-header">
  <h1>Kategorien anlegen</h1>
</div>

<p>
  <a href="<?= $listLink ?>" class="btn btn-default">
    <i class="fa fa-list"></i>
    <span class="hidden-xs hidden-sm">Übersicht</span>
  </a>
</p>
<div class="well">
  <?= $this->form()->openTag($form); ?>
  <?= $this->formElement($form->get('csrf')); ?>
  <div class="form-group">
    <?= $this->formLabel($form->get('status')); ?>
    <div class="col-sm-10">
      <?= $this->formElement($form->get('status')); ?>
      <?= $this->formElementErrors($form->get('status')); ?>
    </div>
  </div>
  <div class="form-group">
    <?= $this->formLabel($form->get('name')); ?>
    <div class="col-sm-10">
      <?= $this->formElement($form->get('name')); ?>
      <?= $this->formElementErrors($form->get('name')); ?>
    </div>
  </div>
  <div class="form-group">
    <?= $this->formLabel($form->get('description')); ?>
    <div class="col-sm-10">
      <?= $this->formElement($form->get('description')); ?>
      <?= $this->formElementErrors($form->get('description')); ?>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <?= $this->formElement($form->get('save_category')); ?>
    </div>
  </div>
  <?= $this->form()->closeTag(); ?>
</div>
