<?php
/**
 * ZF3 book Simple CMS Training Application
 *
 * @author     Ralf Eggert <ralf@travello.de>
 * @link       https://github.com/zf3buch/simple-cms
 * @license    http://opensource.org/licenses/MIT The MIT License (MIT)
 *
 */

use CategoryModel\Entity\CategoryEntity;

/** @var CategoryEntity $category */
$category = $this->category;

$listLink    = $this->url('category-backend', [], true);
$showLink    = $this->url(
    'category-backend/show', ['id' => $category->getId()], true
);
$editLink    = $this->url(
    'category-backend/modify', ['action' => 'edit', 'id' => $category->getId()], true
);
$deleteLink  = $this->url(
    'category-backend/modify', ['action' => 'delete', 'id' => $category->getId()], true
);
$approveLink = $this->url(
    'category-backend/modify', ['action' => 'approve', 'id' => $category->getId()], true
);
$blockLink   = $this->url(
    'category-backend/modify', ['action' => 'block', 'id' => $category->getId()], true
);

$this->headTitle('category_backend_title_display_block');
$this->h1('category_backend_h1_display_block');
?>
<div class="alert alert-danger">
  <p>
    <strong>
      <?= $this->translate('category_backend_message_block_category') ?>
    </strong>
  </p>
  <p>
    <a class="btn btn-danger"
       href="<?= $blockLink ?>?block=yes">
      <?= $this->translate('category_backend_action_block') ?>
    </a>
    <a class="btn btn-default" href="<?= $showLink ?>">
      <?= $this->translate('category_backend_action_cancel') ?>
    </a>
  </p>
</div>
<p>
  <a href="<?= $showLink ?>" class="btn btn-default">
    <i class="fa fa-file-text-o"></i>
    <span class="hidden-xs hidden-sm">
      <?= $this->translate('category_backend_action_show_short') ?>
    </span>
  </a>
  <a href="<?= $editLink ?>" class="btn btn-default">
    <i class="fa fa-pencil"></i>
    <span class="hidden-xs hidden-sm">
      <?= $this->translate('category_backend_action_edit_short') ?>
    </span>
  </a>
  <a href="<?= $deleteLink ?>" class="btn btn-default">
    <i class="fa fa-trash-o"></i>
    <span class="hidden-xs hidden-sm">
      <?= $this->translate('category_backend_action_delete_short') ?>
    </span>
  </a>
  <a href="<?= $approveLink ?>" class="btn btn-default">
    <i class="fa fa-thumbs-o-up"></i>
    <span class="hidden-xs hidden-sm">
      <?= $this->translate('category_backend_action_approve_short') ?>
    </span>
  </a>
  <a href="<?= $blockLink ?>" class="btn btn-primary">
    <i class="fa fa-thumbs-o-down"></i>
    <span class="hidden-xs hidden-sm">
      <?= $this->translate('category_backend_action_block_short') ?>
    </span>
  </a>
  <a href="<?= $listLink ?>" class="btn btn-default">
    <i class="fa fa-list"></i>
    <span class="hidden-xs hidden-sm">
      <?= $this->translate('category_backend_action_overview') ?>
    </span>
  </a>
</p>
<div class="well">
  <form class="form-horizontal">
    <div class="form-group">
      <label class="col-sm-2 control-label">
        <?= $this->translate('category_backend_label_image') ?>
      </label>
      <div class="col-sm-10 form-control-static">
        <img src="<?= $category->getImage() ?>" class="row col-xs-3 img-responsive">
      </div>
    </div>
    <div class="form-group">
      <label class="col-sm-2 control-label">
        <?= $this->translate('category_backend_label_updated') ?>
      </label>
      <div class="col-sm-10 form-control-static">
        <?= $this->dateFormat(
            $category->getUpdated(),
            IntlDateFormatter::MEDIUM,
            IntlDateFormatter::MEDIUM
        )  ?>
      </div>
    </div>
    <div class="form-group">
      <label class="col-sm-2 control-label">
        <?= $this->translate('category_backend_label_status') ?>
      </label>
      <div class="col-sm-10 form-control-static">
        <?= $this->translate(
            'category_model_option_status_' . $category->getStatus()
        ) ?>
      </div>
    </div>
    <div class="form-group">
      <label class="col-sm-2 control-label">
        <?= $this->translate('category_backend_label_name') ?>
      </label>
      <div class="col-sm-10 form-control-static">
        <?= $category->getName() ?>
      </div>
    </div>
    <div class="form-group">
      <label class="col-sm-2 control-label">
        <?= $this->translate('category_backend_label_description') ?>
      </label>
      <div class="col-sm-10 form-control-static">
        <?= $category->getDescription() ?>
      </div>
    </div>
  </form>
</div>
