<?php
/**
 * ZF3 book Simple CMS Training Application
 *
 * @author     Ralf Eggert <ralf@travello.de>
 * @link       https://github.com/zf3buch/simple-cms
 * @license    http://opensource.org/licenses/MIT The MIT License (MIT)
 *
 */

use CategoryBackend\Form\CategoryFormInterface;
use CategoryModel\Entity\CategoryEntity;

/** @var CategoryFormInterface $form */
$form = $this->categoryForm;

/** @var CategoryEntity $category */
$category = $this->category;

$listLink    = $this->url('category-backend', [], true);
$showLink    = $this->url(
    'category-backend/show', ['id' => $category->getId()], true
);
$editLink    = $this->url(
    'category-backend/modify', ['action' => 'edit', 'id' => $category->getId()], true
);
$deleteLink  = $this->url(
    'category-backend/modify', ['action' => 'delete', 'id' => $category->getId()], true
);
$approveLink = $this->url(
    'category-backend/modify', ['action' => 'approve', 'id' => $category->getId()], true
);
$blockLink   = $this->url(
    'category-backend/modify', ['action' => 'block', 'id' => $category->getId()], true
);

$this->headTitle('category_backend_title_display_edit');
$this->h1('category_backend_h1_display_edit');

$this->inlineScript()->prependFile(
    '/assets/vendor/ckeditor/ckeditor.js', 'text/javascript'
);
$this->inlineScript()->appendScript('CKEDITOR.replace("category_description");');
?>
<p>
  <a href="<?= $showLink ?>" class="btn btn-default">
    <i class="fa fa-file-text-o"></i>
    <span class="hidden-xs hidden-sm">
      <?= $this->translate('category_backend_action_show_short') ?>
    </span>
  </a>
  <a href="<?= $editLink ?>" class="btn btn-primary">
    <i class="fa fa-pencil"></i>
    <span class="hidden-xs hidden-sm">
      <?= $this->translate('category_backend_action_edit_short') ?>
    </span>
  </a>
  <a href="<?= $deleteLink ?>" class="btn btn-default">
    <i class="fa fa-trash-o"></i>
    <span class="hidden-xs hidden-sm">
      <?= $this->translate('category_backend_action_delete_short') ?>
    </span>
  </a>
  <a href="<?= $approveLink ?>" class="btn btn-default">
    <i class="fa fa-thumbs-o-up"></i>
    <span class="hidden-xs hidden-sm">
      <?= $this->translate('category_backend_action_approve_short') ?>
    </span>
  </a>
  <a href="<?= $blockLink ?>" class="btn btn-default">
    <i class="fa fa-thumbs-o-down"></i>
    <span class="hidden-xs hidden-sm">
      <?= $this->translate('category_backend_action_block_short') ?>
    </span>
  </a>
  <a href="<?= $listLink ?>" class="btn btn-default">
    <i class="fa fa-list"></i>
    <span class="hidden-xs hidden-sm">
      <?= $this->translate('category_backend_action_overview') ?>
    </span>
  </a>
</p>
<?php
$staticElements = [
    [
        'label' => $this->translate('category_backend_label_image'),
        'value' => '<img src="' . $category->getImage()
            . '" class="row col-xs-3 img-responsive">',
    ],
    [
        'label' => $this->translate('category_backend_label_updated'),
        'value' => $this->dateFormat(
            $category->getUpdated(),
            IntlDateFormatter::MEDIUM,
            IntlDateFormatter::MEDIUM
        ),
    ],
    [
        'label' => $this->translate('category_backend_label_status'),
        'value' => $this->translate(
            'category_model_option_status_' . $category->getStatus()
        ),
    ],
];
?>
<div class="well" style="position: relative">
  <?= $this->bootstrapForm($form, $staticElements); ?>
</div>
