<?php
/**
 * ZF3 book Simple CMS Training Application
 *
 * @author     Ralf Eggert <ralf@travello.de>
 * @link       https://github.com/zf3buch/simple-cms
 * @license    http://opensource.org/licenses/MIT The MIT License (MIT)
 *
 */

use CategoryBackend\Form\CategoryFormInterface;
use CategoryModel\Entity\CategoryEntity;

/** @var CategoryFormInterface $form */
$form = $this->categoryForm;

/** @var CategoryEntity $category */
$category = $this->category;

$listLink    = $this->url('category-backend', [], true);
$showLink    = $this->url(
    'category-backend/show', ['id' => $category->getId()], true
);
$editLink    = $this->url(
    'category-backend/modify', ['action' => 'edit', 'id' => $category->getId()], true
);
$deleteLink  = $this->url(
    'category-backend/modify', ['action' => 'delete', 'id' => $category->getId()], true
);
$approveLink = $this->url(
    'category-backend/modify', ['action' => 'approve', 'id' => $category->getId()], true
);
$blockLink   = $this->url(
    'category-backend/modify', ['action' => 'block', 'id' => $category->getId()], true
);

$this->headTitle('Kategorien bearbeiten');
?>
<div class="page-header">
  <h1>Kategorien bearbeiten</h1>
</div>

<p>
  <a href="<?= $showLink ?>" class="btn btn-default">
    <i class="fa fa-file-text-o"></i>
    <span class="hidden-xs hidden-sm">Anzeigen</span>
  </a>
  <a href="<?= $editLink ?>" class="btn btn-primary">
    <i class="fa fa-pencil"></i>
    <span class="hidden-xs hidden-sm">Bearbeiten</span>
  </a>
  <a href="<?= $deleteLink ?>" class="btn btn-default">
    <i class="fa fa-trash-o"></i>
    <span class="hidden-xs hidden-sm">Löschen</span>
  </a>
  <a href="<?= $approveLink ?>" class="btn btn-default">
    <i class="fa fa-thumbs-o-up"></i>
    <span class="hidden-xs hidden-sm">Freigeben</span>
  </a>
  <a href="<?= $blockLink ?>" class="btn btn-default">
    <i class="fa fa-thumbs-o-down"></i>
    <span class="hidden-xs hidden-sm">Sperren</span>
  </a>
  <a href="<?= $listLink ?>" class="btn btn-default">
    <i class="fa fa-list"></i>
    <span class="hidden-xs hidden-sm">Übersicht</span>
  </a>
</p>
<div class="well">
  <?= $this->form()->openTag($form); ?>
  <?= $this->formElement($form->get('csrf')); ?>
  <div class="form-group">
    <label class="col-sm-2 control-label">Bild</label>
    <div class="col-sm-10 form-control-static">
      <img src="<?= $category->getImage() ?>" class="row col-xs-3 img-responsive">
    </div>
  </div>
  <div class="form-group">
    <label class="col-sm-2 control-label">Geändert</label>
    <div class="col-sm-10 form-control-static">
      <?= $category->getUpdated()->format('d.m.Y H:i:s')  ?>
    </div>
  </div>
  <div class="form-group">
    <label class="col-sm-2 control-label">Status</label>
    <div class="col-sm-10 form-control-static">
      <?= $category->getStatus() ?>
    </div>
  </div>
  <div class="form-group">
    <?= $this->formLabel($form->get('name')); ?>
    <div class="col-sm-10">
      <?= $this->formElement($form->get('name')); ?>
      <?= $this->formElementErrors($form->get('name')); ?>
    </div>
  </div>
  <div class="form-group">
    <?= $this->formLabel($form->get('description')); ?>
    <div class="col-sm-10">
      <?= $this->formElement($form->get('description')); ?>
      <?= $this->formElementErrors($form->get('description')); ?>
    </div>
  </div>
  <div class="form-group">
    <?= $this->formLabel($form->get('image')); ?>
    <div class="col-sm-10">
      <?= $this->formElement($form->get('image')); ?>
      <?= $this->formElementErrors($form->get('image')); ?>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <?= $this->formElement($form->get('save_category')); ?>
    </div>
  </div>
  <?= $this->form()->closeTag(); ?>
</div>