<?php
/**
 * ZF3 book Simple CMS Training Application
 *
 * @author     Ralf Eggert <ralf@travello.de>
 * @link       https://github.com/zf3buch/simple-cms
 * @license    http://opensource.org/licenses/MIT The MIT License (MIT)
 */
?>
<footer id="footer">
  <div class="footer-top"></div>
  <div class="container">
    <div class="row">
      <div class="col-lg-4">
        <h4>
          Simple CMS
        </h4>
        <p>
          Dieses Demoprojekt basiert auf der erweiterten <strong>Zend
          Framework Skeleton Application</strong>, die das ZF bereitstellt,
          damit Sie schnell eigene Zend Framework 3 MVC Anwendungen
          erstellen können. Dieses Demoprojekt dient nur als Beispiel, die
          Inhalte und Bilder sind rein <strong>fiktiv</strong>.
        </p>
      </div>
      <div class="col-lg-4">
        <h4>
          Zend Framework Links
        </h4>
        <ul>
          <li>
            <a href="http://framework.zend.com/" target="_blank">
              Zend Framework Website
            </a>
          </li>
          <li>
            <a href="http://modules.zendframework.com/" target="_blank">
              Zend Framework Module
            </a>
          </li>
          <li>
            <a href="https://github.com/zendframework/" target="_blank">
              Zend Framework Github
            </a>
          </li>
        </ul>
        </div>
        <div class="col-lg-4">
        <h4>
          ZF3buch Links
        </h4>
        <ul>
          <li>
            <a href="http://www.zendframeworkbuch.de/" target="_blank">
              Website zum ZF3 Buch
            </a>
          </li>
          <li>
            <a href="https://github.com/zf3buch/simple-cms"
               target="_blank">
              GitHub Repository Simple CMS
            </a>
          </li>
          <li>
            <a href="http://www.ralfeggert.de" target="_blank">
              Homepage Ralf Eggert
            </a>
          </li>
        </ul>
      </div>
    </div>
  </div>
</footer>
