<?php
/**
 * ZF3 book Simple CMS Training Application
 *
 * @author     Ralf Eggert <ralf@travello.de>
 * @link       https://github.com/zf3buch/simple-cms
 * @license    http://opensource.org/licenses/MIT The MIT License (MIT)
 *
 */

use PageModel\Entity\PageEntity;

/** @var PageEntity $page */
$page = $this->page;

$listLink    = $this->url('page-backend', [], true);
$showLink    = $this->url(
    'page-backend/show', ['id' => $page->getId()], true
);
$editLink    = $this->url(
    'page-backend/modify', ['action' => 'edit', 'id' => $page->getId()], true
);
$deleteLink  = $this->url(
    'page-backend/modify', ['action' => 'delete', 'id' => $page->getId()], true
);
$approveLink = $this->url(
    'page-backend/modify', ['action' => 'approve', 'id' => $page->getId()], true
);
$blockLink   = $this->url(
    'page-backend/modify', ['action' => 'block', 'id' => $page->getId()], true
);

$this->headTitle('page_backend_title_display_show');
$this->h1('page_backend_h1_display_show');
?>
<p>
  <a href="<?= $showLink ?>" class="btn btn-primary">
    <i class="fa fa-file-text-o"></i>
    <span class="hidden-xs hidden-sm">
      <?= $this->translate('page_backend_action_show_short') ?>
    </span>
  </a>
  <a href="<?= $editLink ?>" class="btn btn-default">
    <i class="fa fa-pencil"></i>
    <span class="hidden-xs hidden-sm">
      <?= $this->translate('page_backend_action_edit_short') ?>
    </span>
  </a>
  <a href="<?= $deleteLink ?>" class="btn btn-default">
    <i class="fa fa-trash-o"></i>
    <span class="hidden-xs hidden-sm">
      <?= $this->translate('page_backend_action_delete_short') ?>
    </span>
  </a>
  <a href="<?= $approveLink ?>" class="btn btn-default">
    <i class="fa fa-thumbs-o-up"></i>
    <span class="hidden-xs hidden-sm">
      <?= $this->translate('page_backend_action_approve_short') ?>
    </span>
  </a>
  <a href="<?= $blockLink ?>" class="btn btn-default">
    <i class="fa fa-thumbs-o-down"></i>
    <span class="hidden-xs hidden-sm">
      <?= $this->translate('page_backend_action_block_short') ?>
    </span>
  </a>
  <a href="<?= $listLink ?>" class="btn btn-default">
    <i class="fa fa-list"></i>
    <span class="hidden-xs hidden-sm">
      <?= $this->translate('page_backend_action_overview') ?>
    </span>
  </a>
</p>
<div class="well">
  <form class="form-horizontal">
    <div class="form-group">
      <label class="col-sm-2 control-label">
        <?= $this->translate('page_backend_label_category') ?>
      </label>
      <div class="col-sm-10 form-control-static">
        <?= $page->getCategory()->getName() ?>
      </div>
    </div>
    <div class="form-group">
      <label class="col-sm-2 control-label">
        <?= $this->translate('page_backend_label_created') ?>
      </label>
      <div class="col-sm-10 form-control-static">
        <?= $page->getCreated()->format('d.m.Y H:i:s') ?>
      </div>
    </div>
    <div class="form-group">
      <label class="col-sm-2 control-label">
        <?= $this->translate('page_backend_label_updated') ?>
      </label>
      <div class="col-sm-10 form-control-static">
        <?= $page->getUpdated()->format('d.m.Y H:i:s') ?>
      </div>
    </div>
    <div class="form-group">
      <label class="col-sm-2 control-label">
        <?= $this->translate('page_backend_label_status') ?>
      </label>
      <div class="col-sm-10 form-control-static">
        <?= $this->translate(
            'page_model_option_status_' . $page->getStatus()
        ) ?>
      </div>
    </div>
    <div class="form-group">
      <label class="col-sm-2 control-label">
        <?= $this->translate('page_backend_label_author') ?>
      </label>
      <div class="col-sm-10 form-control-static">
        <?= $page->getAuthor() ?>
      </div>
    </div>
    <div class="form-group">
      <label class="col-sm-2 control-label">
        <?= $this->translate('page_backend_label_title') ?>
      </label>
      <div class="col-sm-10 form-control-static">
        <?= $page->getTitle() ?>
      </div>
    </div>
    <div class="form-group">
      <label class="col-sm-2 control-label">
        <?= $this->translate('page_backend_label_text') ?>
      </label>
      <div class="col-sm-10 form-control-static">
        <?= $page->getText() ?>
      </div>
    </div>
  </form>
</div>
