<?php
/**
 * ZF3 book Simple CMS Training Application
 *
 * @author     Ralf Eggert <ralf@travello.de>
 * @link       https://github.com/zf3buch/simple-cms
 * @license    http://opensource.org/licenses/MIT The MIT License (MIT)
 *
 */

use CategoryModel\Entity\CategoryEntity;

$addLink = $this->url(
    'category-backend/modify', ['action' => 'add'], true
);

$this->headTitle('Kategorien administrieren');
?>
<div class="page-header">
  <h1>Kategorien administrieren</h1>
</div>

<table class="table table-condensed table-bordered table-striped">
  <thead>
  <tr>
    <th>Status</th>
    <th>Name</th>
    <th class="hidden-xs">Beschreibung</th>
    <th class="hidden-xs">Datum</th>
    <th class="text-center">
      <a href="<?= $addLink ?>">
        <i class="fa fa-plus-square-o"></i>
      </a>
    </th>
  </tr>
  </thead>
  <tbody>
  <?php /** @var CategoryEntity $category */ ?>
  <?php foreach ($this->categoryList as $category) : ?>
    <?php
    $showLink    = $this->url(
        'category-backend/show', ['id' => $category->getId()], true
    );
    $editLink    = $this->url(
        'category-backend/modify',
        ['action' => 'edit', 'id' => $category->getId()], true
    );
    $deleteLink  = $this->url(
        'category-backend/modify',
        ['action' => 'delete', 'id' => $category->getId()], true
    );
    $approveLink = $this->url(
        'category-backend/modify',
        ['action' => 'approve', 'id' => $category->getId()], true
    );
    $blockLink   = $this->url(
        'category-backend/modify',
        ['action' => 'block', 'id' => $category->getId()], true
    );
    ?>
    <tr>
      <td>
        <?= $category->getStatus() ?>
      </td>
      <td>
        <a href="<?= $showLink ?>">
          <?= $category->getName() ?>
        </a>
      </td>
      <td class="hidden-xs">
        <?= $category->getDescription() ?>
      </td>
      <td class="hidden-xs">
        <?= $category->getUpdated()->format('d.m.Y H:i:s') ?>
      </td>
      <td class="text-center">
        <a href="<?= $showLink ?>" class="hidden-xs hidden-sm">
          <i class="fa fa-file-text-o"></i>
        </a>
        <a href="<?= $editLink ?>">
            <i class="fa fa-pencil"></i>
        </a>
        <a href="<?= $deleteLink ?>" class="hidden-xs hidden-sm">
          <i class="fa fa-trash-o"></i>
        </a>
        <a href="<?= $approveLink ?>" class="visible-lg-inline">
          <i class="fa fa-thumbs-o-up"></i>
        </a>
        <a href="<?= $blockLink ?>" class="visible-lg-inline">
         <i class="fa fa-thumbs-o-down"></i>
        </a>
      </td>
    </tr>
  <?php endforeach; ?>
  </tbody>
</table>
<nav class="text-center">
  <?php
  echo $this->paginationControl(
      $this->categoryList,
      'Sliding',
      'pagination/page-navigation',
      [
        'route' => 'category-backend/page'
      ]
  );
  ?>
</nav>
