<?php
/**
 * ZF3 book Simple CMS Training Application
 *
 * @author     Ralf Eggert <ralf@travello.de>
 * @link       https://github.com/zf3buch/simple-cms
 * @license    http://opensource.org/licenses/MIT The MIT License (MIT)
 */

?>
<div class="page-header">
  <h1>Willkommen zum Simple CMS!</h1>
</div>

<div class="well text-center">
  <h3>
    <i class="fa fa-hourglass fa-spin"></i>
    &nbsp; In Kürze mehr &nbsp;
    <i class="fa fa-hourglass fa-spin"></i>
  </h3>
</div>
