<?php
/**
 * ZF3 book Simple CMS Training Application
 *
 * @author     Ralf Eggert <ralf@travello.de>
 * @link       https://github.com/zf3buch/simple-cms
 * @license    http://opensource.org/licenses/MIT The MIT License (MIT)
 */

?>
<div class="page-header">
  <h1>Willkommen zum Simple CMS!</h1>
</div>

<div class="row">
  <?php foreach ($this->randomPages as $page) : ?>
    <?php
      $text = strip_tags($page['text']);
      $text = implode(' ', array_slice(explode(' ', $text), 0, 50));

      $pageUrl     = $this->url('page', ['url' => $page['url']], true);
      $categoryUrl = $this->url(
          'category', ['url' => $page['category']['url']], true
      );
    ?>
    <div class="col-sm-6">
      <div class="panel panel-primary">
        <div class="panel-heading clearfix">
          <strong>
            <a href="<?= $pageUrl; ?>">
              <?= $page['title'] ?>
            </a>
          </strong>
        </div>
        <div class="panel-body">
          <div class="col-sm-4">
            <img src="<?= $page['category']['image'] ?>"
                 class="img-responsive center-block">
          </div>
          <p><?= $text; ?> ...</p>
          <p class="text-center">
            <a href="<?= $pageUrl; ?>" class="btn btn-primary">
              Seite anzeigen
            </a>
            <a href="<?= $categoryUrl; ?>" class="btn btn-primary">
              Alle <?= $page['category']['name'] ?> Seiten
            </a>
          </p>
        </div>
      </div>
    </div>
  <?php endforeach; ?>
</div>