<?php
/**
 * ZF3 book Simple CMS Training Application
 *
 * @author     Ralf Eggert <ralf@travello.de>
 * @link       https://github.com/zf3buch/simple-cms
 * @license    http://opensource.org/licenses/MIT The MIT License (MIT)
 */

use PageModel\Entity\PageEntity;

$this->h1($this->translate('application_h1_index_index'));
?>
<div class="row">
  <?php /** @var PageEntity $page */ ?>
  <?php foreach ($this->randomPages as $page) : ?>
    <?php
      $text = strip_tags($page->getText());
      $text = implode(' ', array_slice(explode(' ', $text), 0, 50));

      $pageUrl     = $this->url('page', ['url' => $page->getUrl()], true);
      $categoryUrl = $this->url(
          'category', ['url' => $page->getCategory()->getUrl()], true
      );
    ?>
    <div class="col-sm-6">
      <div class="panel panel-primary">
        <div class="panel-heading clearfix">
          <strong>
            <a href="<?= $pageUrl; ?>">
              <?= $page->getTitle() ?>
            </a>
          </strong>
        </div>
        <div class="panel-body">
          <div class="col-sm-4">
            <img src="<?= $page->getCategory()->getImage() ?>"
                 class="img-responsive center-block">
          </div>
          <p><?= $text; ?> ...</p>
          <p class="text-center">
            <a href="<?= $pageUrl; ?>" class="btn btn-primary">
              <?= $this->translate('page_frontend_action_show_page') ?>
            </a>
            <a href="<?= $categoryUrl; ?>" class="btn btn-primary">
              <?= sprintf(
                  $this->translate('page_frontend_action_show_category'),
                  $page->getCategory()->getName()
              ) ?>
            </a>
          </p>
        </div>
      </div>
    </div>
  <?php endforeach; ?>
</div>
